/**
 * COCO dataset class names and category mappings for YOLOv11 object detection.
 *
 * The 80 COCO classes in their canonical order (matching model output indices).
 */

export const COCO_CLASSES: string[] = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
];

/**
 * Maps each COCO class name to a home-inventory category.
 *
 * Categories align with the CATEGORIES constant in src/utils/constants.ts.
 */
export const COCO_CLASS_TO_CATEGORY: Record<string, string> = {
  // People
  person: 'Personal',

  // Vehicles / outdoor
  bicycle: 'Sports',
  car: 'Automotive',
  motorcycle: 'Automotive',
  airplane: 'Miscellaneous',
  bus: 'Automotive',
  train: 'Miscellaneous',
  truck: 'Automotive',
  boat: 'Miscellaneous',

  // Street objects
  'traffic light': 'Miscellaneous',
  'fire hydrant': 'Miscellaneous',
  'stop sign': 'Miscellaneous',
  'parking meter': 'Miscellaneous',
  bench: 'Furniture',

  // Animals
  bird: 'Miscellaneous',
  cat: 'Miscellaneous',
  dog: 'Miscellaneous',
  horse: 'Miscellaneous',
  sheep: 'Miscellaneous',
  cow: 'Miscellaneous',
  elephant: 'Miscellaneous',
  bear: 'Miscellaneous',
  zebra: 'Miscellaneous',
  giraffe: 'Miscellaneous',

  // Accessories / bags
  backpack: 'Personal',
  umbrella: 'Personal',
  handbag: 'Personal',
  tie: 'Clothing',
  suitcase: 'Personal',

  // Sports
  frisbee: 'Sports',
  skis: 'Sports',
  snowboard: 'Sports',
  'sports ball': 'Sports',
  kite: 'Sports',
  'baseball bat': 'Sports',
  'baseball glove': 'Sports',
  skateboard: 'Sports',
  surfboard: 'Sports',
  'tennis racket': 'Sports',

  // Kitchen / dining
  bottle: 'Kitchen',
  'wine glass': 'Kitchen',
  cup: 'Kitchen',
  fork: 'Kitchen',
  knife: 'Kitchen',
  spoon: 'Kitchen',
  bowl: 'Kitchen',

  // Food
  banana: 'Kitchen',
  apple: 'Kitchen',
  sandwich: 'Kitchen',
  orange: 'Kitchen',
  broccoli: 'Kitchen',
  carrot: 'Kitchen',
  'hot dog': 'Kitchen',
  pizza: 'Kitchen',
  donut: 'Kitchen',
  cake: 'Kitchen',

  // Furniture
  chair: 'Furniture',
  couch: 'Furniture',
  'potted plant': 'Decor',
  bed: 'Furniture',
  'dining table': 'Furniture',
  toilet: 'Bathroom',

  // Electronics
  tv: 'Electronics',
  laptop: 'Electronics',
  mouse: 'Electronics',
  remote: 'Electronics',
  keyboard: 'Electronics',
  'cell phone': 'Electronics',
  microwave: 'Electronics',
  oven: 'Electronics',
  toaster: 'Electronics',
  sink: 'Kitchen',
  refrigerator: 'Electronics',

  // Misc household
  book: 'Books',
  clock: 'Decor',
  vase: 'Decor',
  scissors: 'Tools',
  'teddy bear': 'Toys',
  'hair drier': 'Personal',
  toothbrush: 'Bathroom',
};
